umps(solution["distribution_plan"], indent=2, ensure_ascii=False), encoding="utf-8")
        outputs.append(distribution_path)
        
        # Create summary report
        summary_path = output_dir / "summary_report.md"
        summary_content = self._create_summary_report(solution)
        summary_path.write_text(summary_content, encoding="utf-8")
        outputs.append(summary_path)
        
        # Log this session
        session_data = {
            "action": "video_production_planning",
            "video_type": solution["video_type"],
            "duration": solution["duration"],
            "scene_count": solution["scene_count"],
            "files_created": [str(p) for p in outputs],
            "budget_estimate": solution["production_plan"]["budget_estimate"]["total"],
            "timeline": solution["production_plan"]["timeline"]["total"]
        }
        
        self.log_session(session_data)
        
        print(f"✅ Video production documents created in: {output_dir}")
        return outputs
    
    def _create_summary_report(self, solution: Dict[str, Any]) -> str:
        """Create summary report"""
        report = f"# Treqe Video Production Summary\n\n"
        report += f"**Created:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        report += f"**Video Type:** {solution['video_type'].replace('_', ' ').title()}\n"
        report += f"**Duration:** {solution['duration']}\n"
        report += f"**Scenes:** {solution['scene_count']}\n\n"
        
        report += "## 📋 Project Overview\n\n"
        report += f"**Title:** {solution['concept']['title']}\n"
        report += f"**Tagline:** {solution['concept']['tagline']}\n"
        report += f"**Target Audience:** {solution['concept']['target_audience']}\n\n"
        
        report += "## 🎬 Story Arc\n\n"
        for key, value in solution['concept']['story_arc'].items():
            report += f"**{key.replace('_', ' ').title()}:** {value}\n"
        
        report += "\n## 💰 Budget Estimate\n\n"
        for category, amount in solution['production_plan']['budget_estimate'].items():
            report += f"**{category.replace('_', ' ').title()}:** {amount}\n"
        
        report += "\n## 📅 Timeline\n\n"
        for phase, duration in solution['production_plan']['timeline'].items():
            report += f"**{phase.replace('_', ' ').title()}:** {duration}\n"
        
        report += "\n## 👥 Team Requirements\n\n"
        for role in solution['production_plan']['team_requirements'][:5]:  # Show first 5
            report += f"• **{role['role']}:** {role['days']} days - {role['responsibility']}\n"
        
        report += "\n## 📊 Distribution Strategy\n\n"
        report += f"**Primary Platform:** {solution['distribution_plan']['primary_platform'].title()}\n"
        report += "**Platforms Covered:** " + ", ".join(solution['distribution_plan']['platform_strategies'].keys()) + "\n"
        
        report += "\n## 🚀 Next Steps\n\n"
        for i, step in enumerate(solution['next_steps'], 1):
            report += f"{i}. {step}\n"
        
        report += "\n## 📁 Files Created\n\n"
        for file in solution['files_to_create']:
            report += f"• `{file}`\n"
        
        report += "\n---\n"
        report += "*This document was generated by the Video Producer Sub-Agent*\n"
        
        return report
    
    def run_demo(self) -> bool:
        """Run a demonstration of Video Producer capabilities"""
        print(f"\n{'='*60}")
        print(f"🎬 DEMO: Video Producer Sub-Agent")
        print(f"{'='*60}")
        
        # Show capabilities
        print(f"\n🔧 Capabilities:")
        for i, capability in enumerate(self.get_capabilities()[:5], 1):  # Show first 5
            print(f"  {i}. {capability}")
        
        # Show integration
        print(f"\n🔄 Ecosystem Integration:")
        for system, integrations in self.get_integration_points().items():
            print(f"  • {system}: {', '.join(integrations[:2])}...")
        
        # Analyze needs
        print(f"\n📊 Analyzing video needs for investor pitch...")
        needs = self.analyze_video_needs(video_type="investor_pitch", platform="multi_platform")
        print(f"  • Type: {needs['video_type'].replace('_', ' ').title()}")
        print(f"  • Duration: {needs['duration_target']}")
        print(f"  • Audience: {needs['audience']}")
        print(f"  • Purpose: {needs['purpose']}")
        
        # Create concept
        print(f"\n💡 Creating video concept...")
        concept = self.create_video_concept(needs)
        print(f"  • Title: {concept['title']}")
        print(f"  • Tagline: {concept['tagline']}")
        print(f"  • Scenes: {len(concept['key_scenes'])}")
        
        # Create script
        print(f"\n📝 Creating script...")
        script = self.create_script(concept)
        print(f"  • Total duration: {script['formatted_duration']}")
        print(f"  • Voiceover lines: {len(script['voiceover_script'])}")
        
        # Show sample scene
        print(f"\n📄 Sample Scene (Scene 3):")
        sample_scene = next((s for s in script['timing_breakdown'] if s['scene'] == 3), None)
        if sample_scene:
            print(f"  • Time: {sample_scene['start']} - {sample_scene['end']}")
            print(f"  • Voiceover: {script['voiceover_script'][2][:60]}...")
        
        # Create production plan
        print(f"\n🏗️ Creating production plan...")
        storyboard = self.create_storyboard(script)
        production_plan = self.create_production_plan(storyboard)
        print(f"  • Timeline: {production_plan['timeline']['total']}")
        print(f"  • Budget: {production_plan['budget_estimate']['total']}")
        print(f"  • Team: {len(production_plan['team_requirements'])} roles")
        
        # Create outputs
        print(f"\n💾 Creating output files...")
        solution = self.generate_solution({"video_type": "investor_pitch", "platform": "multi_platform"})
        outputs = self.create_outputs(solution)
        
        print(f"\n✅ Demo completed successfully!")
        print(f"📁 Outputs created in: {self.agent_dir}")
        print(f"📄 Key files created:")
        key_files = ["video_concept.json", "script.json", "production_plan.json", "summary_report.md"]
        for file in key_files:
            file_path = self.agent_dir / "outputs" / file
            if file_path.exists():
                print(f"  • {file}")
        
        # Show status
        status = self.get_status()
        print(f"\n📊 Agent Status:")
        print(f"  • Outputs: {status['outputs_count']} files")
        print(f"  • Sessions: {status['sessions_count']} logged")
        print(f"  • Status: {status['status']}")
        
        return True


# Main execution
if __name__ == "__main__":
    # Create and run Video Producer agent
    video_producer = VideoProducerAgent()
    
    # Run demo
    success = video_producer.run_demo()
    
    if success:
        print(f"\n{'='*60}")
        print(f"🎬 Video Producer ready for Treqe video production!")
        print(f"{'='*60}")
        print(f"\nNext steps:")
        print(f"1. Review concept in: {video_producer.agent_dir}/outputs/video_concept.json")
        print(f"2. Finalize script with stakeholders")
        print(f"3. Begin pre-production based on production plan")
        print(f"4. Start distribution planning")
        print(f"5. Schedule production timeline")
    else:
        print(f"\n❌ Demo failed. Check logs for details.")